title = "configuration of rsync-os"

# [object storage's name] 
[minio]
  endpoint = "127.0.0.1:9000"
  keyAccess = "minioadmin"
  keySecret = "minioadmin"
  bucket = "mirrorsync"
  [minio.boltdb]
    path = "test.db"
