// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.0
// source: finfo.proto

package fldb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size  int64 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Mtime int32 `protobuf:"varint,2,opt,name=Mtime,proto3" json:"Mtime,omitempty"`
	Mode  int32 `protobuf:"varint,3,opt,name=Mode,proto3" json:"Mode,omitempty"` // hash 16bytes
}

func (x *FInfo) Reset() {
	*x = FInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FInfo) ProtoMessage() {}

func (x *FInfo) ProtoReflect() protoreflect.Message {
	mi := &file_finfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FInfo.ProtoReflect.Descriptor instead.
func (*FInfo) Descriptor() ([]byte, []int) {
	return file_finfo_proto_rawDescGZIP(), []int{0}
}

func (x *FInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FInfo) GetMtime() int32 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *FInfo) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

var File_finfo_proto protoreflect.FileDescriptor

var file_finfo_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x05, 0x46, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4d, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x69, 0x61, 0x6b, 0x7a,
	0x2f, 0x72, 0x73, 0x79, 0x6e, 0x63, 0x32, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x64, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finfo_proto_rawDescOnce sync.Once
	file_finfo_proto_rawDescData = file_finfo_proto_rawDesc
)

func file_finfo_proto_rawDescGZIP() []byte {
	file_finfo_proto_rawDescOnce.Do(func() {
		file_finfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_finfo_proto_rawDescData)
	})
	return file_finfo_proto_rawDescData
}

var file_finfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_finfo_proto_goTypes = []interface{}{
	(*FInfo)(nil), // 0: proto.FInfo
}
var file_finfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_finfo_proto_init() }
func file_finfo_proto_init() {
	if File_finfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_finfo_proto_goTypes,
		DependencyIndexes: file_finfo_proto_depIdxs,
		MessageInfos:      file_finfo_proto_msgTypes,
	}.Build()
	File_finfo_proto = out.File
	file_finfo_proto_rawDesc = nil
	file_finfo_proto_goTypes = nil
	file_finfo_proto_depIdxs = nil
}
